# Generated by Django 3.2.8 on 2021-12-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_guest', models.EmailField(blank=True, max_length=254)),
                ('topic', models.CharField(max_length=200)),
                ('message_text', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'profile'},
        ),
    ]
