# Generated by Django 3.2.8 on 2021-12-12 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_remove_order_total_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'order'},
        ),
    ]
