# Generated by Django 3.2.8 on 2021-12-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_alter_order_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='user',
        ),
    ]
