# Generated by Django 3.2.8 on 2021-12-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_rename_customer_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='number_of',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
        migrations.AddField(
            model_name='order',
            name='apartment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='city_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='home_number',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='name1',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='name2',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default='', max_length=6),
        ),
    ]
