# Generated by Django 3.2.8 on 2022-01-23 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0011_product_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=10, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, verbose_name='Dostępność'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='medapp.category', verbose_name='Kategoria produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='city',
            field=models.CharField(default='', max_length=200, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, verbose_name='Opis produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d', verbose_name='Zdjęcie produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nazwa produktu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cena za dzień'),
        ),
    ]
